[package]
name = "dubbo-metadata"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
description = "dubbo-rust-metadata"
repository = "https://github.com/apache/dubbo-rust.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
