logging:
  level: debug
dubbo:
  protocols:
    triple:
      ip: 0.0.0.0
      port: '8888'
      name: tri
  registries:
    demoZK:
      protocol: zookeeper
      address: 0.0.0.0:2181
  provider:
    services:
      GreeterProvider:
        version: 1.0.0
        group: test
        protocol: triple
        interface: org.apache.dubbo.sample.tri.Greeter
  consumer:
    references:
      - url: tri://localhost:20000
        interface: org.apache.dubbo.sample.tri.Greeter
        protocol: tri
        coding: proto
        compress: false
      - url: tri://localhost:20000
        interface: grpc.examples.echo.Echo
        protocol: tri
        coding: proto
        compress: true