[package]
name = "triple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = {version = "0.3", optional = true}
hyper = {version="0.14.19", features = ["full"]}
http = "0.2"
tonic = {version ="0.7.2", features = ["compression",]}
tower-service = "0.3.1"
http-body = "0.4.4"
tower = "0.4.12"
futures-util = {version = "0.3", default-features = false}
futures-core = {version = "0.3", default-features = false}
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net", "signal"] }
prost-derive = {version = "0.10", optional = true}
prost = "0.10.4"
prost-types = { version = "0.6", default-features = false }
lazy_static = "1.3.0"
async-trait = "0.1.56"
tower-layer = "0.3"
pin-project = "1.0"
axum = "0.5.9"
bytes = "1.0"
serde_json = "1.0.82"
serde = {version="1.0.138", features = ["derive"]}
async-stream = "0.3"
tokio-stream = "0.1"
flate2 = "1.0"
tracing = "0.1"

# for test in codegen
config = {path = "../config"}
