[package]
name = "config_center"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etcd-client = "0.9.2"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1.56"
rand = "0.8.5"
