logging:
  level: debug
dubbo:
  protocols:
    triple:
      ip: 0.0.0.0
      port: '8888'
      name: tri
  registries:
    demoZK:
      protocol: zookeeper
      address: 0.0.0.0:2181
  provider:
    services:
      DemoServiceImpl:
        version: 1.0.0
        group: test
        protocol: triple
        serialization : fastjson
        interface: org.apache.dubbo.springboot.demo.DemoService
  routers:
    consumer:
      - service: "org.apache.dubbo.springboot.demo.DemoService"
        url: tri://127.0.0.1:20000
        protocol: triple