[package]
name = "remoting-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes.workspace = true
base.workspace = true
thiserror.workspace = true
dashmap.workspace = true
protocol-base.workspace = true
anyhow.workspace = true