[package]
name = "common"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
lazy_static = "1.4.0"
dashmap = "5.4.0"
