[package]
name = "dubbo-runtime"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Stable runtime facade for embedding Dubbo Rust core"
repository = "https://github.com/apache/dubbo-rust.git"

[dependencies]
bytes.workspace = true
dubbo = { path = "../dubbo", version = "0.4.0" }
http = "0.2"

